# -*- coding: utf-8 -*-
"""DownloadDataset.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ilIwDhEU8gqA5cpjBCzrlwLj1O6U8ELO
"""

from google.colab import drive
import pandas as pd
drive.mount('/content/mydrive')

cd /content/mydrive/MyDrive/ShopeeCodeLeague/ML_Sentiment_Label_Model-master

!pwd

with open("data/imdb_labelled.txt", "r") as text_file:
    lines = text_file.read().split("\n")
with open("data/amazon_cells_labelled.txt", "r") as text_file:
    lines = text_file.read().split("\n")
with open("data/yelp_labelled.txt", "r") as text_file:
    lines = text_file.read().split("\n")
newLines = [line.split("\t") for line in lines if len(line.split("t")) == 2 and line.split("\t")[1] != ""]

train_documents = [line[0] for line in newLines]
train_labels = [int(line[1]) for line in newLines]

from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import BernoulliNB

count_vectorizer = CountVectorizer(binary="true")
train_documents = count_vectorizer.fit_transform(train_documents)

classifier = BernoulliNB().fit(train_documents, train_labels)

def predictionOutput(sentence):
    prediction = classifier.predict(count_vectorizer.transform([sentence]))
    if(prediction[0] == 1):
        print("This is a Positive Sentiment Sentence")
    elif (prediction[0] == 0):
        print("This is a Negative Sentiment Sentence")

predictionOutput("I am having a very good and great day")
predictionOutput("This is the worst movie ever!")